CREATE TABLE [dbo].[GBAMemberships] (
    [id]                          NUMERIC (20)   IDENTITY (4187, 1) NOT NULL,
    [customer_id]                 NUMERIC (20)   NOT NULL,
    [user_id]                     NUMERIC (20)   NULL,
    [object_id]                   BIGINT         NOT NULL,
    [object_type]                 NVARCHAR (20)  NULL,
    [currency]                    NVARCHAR (20)  NOT NULL,
    [initial_amount]              NVARCHAR (MAX) NOT NULL,
    [recurring_amount]            NVARCHAR (MAX) NOT NULL,
    [created_date]                DATETIME2 (0)  NULL,
    [activated_date]              DATETIME2 (0)  NULL,
    [trial_end_date]              DATETIME2 (0)  NULL,
    [renewed_date]                DATETIME2 (0)  NULL,
    [cancellation_date]           DATETIME2 (0)  NULL,
    [expiration_date]             DATETIME2 (0)  NULL,
    [payment_plan_completed_date] DATETIME2 (0)  NULL,
    [auto_renew]                  INT            NOT NULL,
    [times_billed]                INT            NOT NULL,
    [maximum_renewals]            INT            NOT NULL,
    [status]                      NVARCHAR (12)  NOT NULL,
    [gateway_customer_id]         NVARCHAR (255) NULL,
    [gateway_subscription_id]     NVARCHAR (255) NULL,
    [gateway]                     NVARCHAR (255) NOT NULL,
    [signup_method]               NVARCHAR (255) NOT NULL,
    [subscription_key]            NVARCHAR (32)  NOT NULL,
    [notes]                       NVARCHAR (MAX) NOT NULL,
    [upgraded_from]               NUMERIC (20)   NULL,
    [date_modified]               DATETIME2 (0)  NULL,
    [disabled]                    INT            NULL,
    [uuid]                        NVARCHAR (100) NOT NULL
);

