CREATE TABLE [dbo].[Members]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	[GBAId] INT NOT NULL, 
    [Name] VARCHAR(50) NOT NULL , 
    [Email] VARCHAR(50) NOT NULL , 
    [Created] DATETIME2 NOT NULL DEFAULT SYSDATETIME(), 
    [LastLogin] DATETIME2 NOT NULL DEFAULT SYSDATETIME(), 
    [StatusId] INT NOT NULL DEFAULT 0, 
    [StatusStr] VARCHAR(20) NOT NULL DEFAULT 'Logged in', 
    CONSTRAINT [AK_Members_GBAId] UNIQUE ([GBAId])
)
