CREATE TABLE [dbo].[TokenTxs]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
    [TxHash] VARCHAR(50) NOT NULL,
    [Token] VARCHAR(10) NOT NULL,
    [FromChain] VARCHAR(50) NOT NULL,
    [FromBlock] INT NOT NULL,
    [FromAddr] VARCHAR(50) NOT NULL, 
    [ToAddr] VARCHAR(50) NOT NULL, 
    [Value] DECIMAL(28,12) NOT NULL, 
    [Memo] VARCHAR(50) NULL , 
    [ClaimBy] INT NULL ,
    [ClaimBlock] INT NULL ,
    [Fee] DECIMAL(28,12) NULL ,
    [DestChain] VARCHAR(50) NULL,
    [DestBlock] INT NULL , 
    [DestAddr] VARCHAR(50) NULL, 
    [Created] DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    [Updated] DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
)
